Done
TID-Lab/aggie pull request #454
Opened 2021-03-15 18:24 UTC by ciabhanconnelly

I think this should work. Having issues pulling from CT on my local machine, as is Johnny, so will need someone to test this. Our issues are unrelated to/persist without this modification.

2021-03-19 17:27 UTC, karpawich requested changes
It looks as though the only change needed for the `secrets.json.example` file is the introduction of the interval key-value pair to the CrowdTangle config object.

2021-03-22 17:09 UTC, karpawich approved these changes

2021-03-22 17:11 UTC, limmabean approved these changes
LGTM

2021-03-22 21:16 UTC, karpawich approved these changes

2021-03-22 21:18 UTC, merged